# Generated by Django 3.1.7 on 2021-04-01 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100)),
                ('users_counter', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('answers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_app.answer')),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_answer', models.PositiveIntegerField()),
                ('mark', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_app.question')),
            ],
        ),
    ]
