# Generated by Django 3.1.7 on 2021-04-01 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('question_app', '0001_initial'),
        ('test_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='test',
            name='test_questions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_app.testquestion'),
        ),
        migrations.AddField(
            model_name='test',
            name='topics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.topic'),
        ),
    ]
